name: Post Caregiving to X

on:
  schedule:
    - cron: '0 8 * * *' # JST 17時
  workflow_dispatch: # 手動トリガー

jobs:
  post-caregiving:
    runs-on: ubuntu-latest

    steps:
      - name: Post Caregiving Content to X
        run: curl -X POST https://nshinri-56d2c5892705.herokuapp.com/api/post-caregiving
