name: Post Cooking to X

on:
  schedule:
    - cron: '0 9 */3 * *' # JST 18時 3日に1回
  workflow_dispatch: # 手動トリガー

jobs:
  post-cooking:
    runs-on: ubuntu-latest

    steps:
      - name: Post Cooking Content to X
        run: curl -X POST https://nshinri-56d2c5892705.herokuapp.com/api/post-cooking
