name: Post Counseling to X

on:
  # schedule:
  #   - cron: '0 10 * * *' # JST 19時
  workflow_dispatch: # 手動トリガー

jobs:
  post-counseling:
    runs-on: ubuntu-latest

    steps:
      - name: Post Counseling Content to X
        run: curl -X POST https://nshinri-56d2c5892705.herokuapp.com/api/post-counseling
